/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.14";
const char *compilation_string = "arm-linux-androideabi-gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/system/etc/wgetrc\" -DLOCALEDIR=\"/system/share/locale\" -I. -I../lib -I../lib -I/opt/android/ev/jb/prebuilts/ndk/current/platforms/android-9/arch-arm/usr/include/ -nostdlib";
const char *link_string = "arm-linux-androideabi-gcc -nostdlib -Wl,-rpath-link=/opt/android/ev/jb/prebuilts/ndk/current/platforms/android-9/arch-arm/usr/lib/ -L/opt/android/ev/jb/prebuilts/ndk/current/platforms/android-9/arch-arm/usr/lib/ -lz -lc ftp-opie.o ../lib/libgnu.a";
